### ISSUE TITLE
论文中似乎有一些小问题

### ISSUE THREAD

**Issue by Dongjiuqing** [yijingru/Vertebra-Landmark-Detection#11]
作者您好，您的文章的方法非常有效。但是在我研究的过程中，发现了一些非常小的问题。
我可视化了三个角最终位置之后，我发现您在表1中的SMAPE_MT和SMAPE_PT的数据应该是写反了。这导致我现在不知怎么办。因为我写的论文使用了您的方法。有可能是您疏忽了。

换句话说，我通过可视化最终三个角度的划分位置，我发现，cobb1和SMAPE1其实是MT的结果，cobb2和SMAPE2是PT的结果。所以，。。。请您检查一下您的代码，您的方法很好，只是结论中我有一点这样疑惑。

**Comment by yijingru** [comment]
您好，时间有些久远记得不太清楚，但是那个结果好像是从 `cobb_evaluate.py `中算出来的，这个代码是从原challenge来的，你看看这个代码是不是有问题呢？MT PT好像跟形状有关

**Comment by Dongjiuqing** [comment]
好的，谢谢。那么应该就没什么问题了。
