### ISSUE TITLE
How does cobb_evaluate work?

### ISSUE THREAD

**Issue by jvkhaw** [yijingru/Vertebra-Landmark-Detection#2]
First and foremost, thank you so much for the great work being done on scoliosis imaging! Could someone please explain to me the three conditions in cobb_angle_calc function in cobb_evaluate.py?

To my understanding, is_S represents defines the spine being S-shaped (meaning very crooked), but what about condition 1 and condition 2? 

Tried the code on some images, and got some confusing results like the green borders at the top? I supposed they're supposed to separate MT, PT and TL, but doesn't seem to be the case.

![is_S](https://user-images.githubusercontent.com/45764352/79852772-b382a380-83f9-11ea-9ff2-d29023bb3dad.png)

**Comment by yijingru** [comment]
Hi, the evaluation code is a python transfer version of the original Matlab code. Maybe you can send email to the hoster of AASCE19 https://aasce19.grand-challenge.org/Contact/.

**Comment by jvkhaw** [comment]
Okay thank you so much!
