### ISSUE TITLE
About the original cobb angle calc

### ISSUE THREAD

**Issue by chriss1245** [yijingru/Vertebra-Landmark-Detection#31]
Very nice work man!

I wanted to ask you about the original source of the cobb_angle_calc function. You mention it was transferred from Matlab. As far as I understood the code, the angle1 seems to be the maximun angle. It is not main thoracic or proximal thoracic or thoracolumbar. 

The second and the third are computed diferently in case the spine has a shape of s. If the shape is not an s, the second is the angle among the first vertebra and the upper vertebra of the first angle, and the third is the angle among the lowest vertebra and the lower vertebra of the first angle.

Right?

When the spine has a shape of s, and the first angle belongs to the lower side of the image, it takes as second angle the maximun possible angle among the top vertebra and the upper vertebra of the first angle. Afterwards, the next angle is the second maximun.

If the spine has a s shape only, it takes as second angle the maximun possible angle in the top, and as third the maximun possible angle at the bottom. 

That may mean that these angle1 angle2 angle3 are not main thoracic, proximal thoracic and tharocolumbar since they may change..

Does this makes sense?

**Comment by yijingru** [comment]
Hello, I remembered the `cobb_angle_calc.py` function was the same as original matlab version, your question may be answered by the challenge host.

**Comment by chriss1245** [comment]
I mailed them, thanks a lot!
