### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Malaika68** [yijingru/Vertebra-Landmark-Detection#4]
Can you please send me link of dataset? I can't find it..

**Comment by yijingru** [comment]
It looks like they removed or updated their sources. You may follow the latest challenges they release, which I didn't pay attention to.

**Comment by Malaika68** [comment]
Okay Thankyou. Can you please tell me what kind of labels are in .mat files?

**Comment by yijingru** [comment]
A list of corner point coordinates of the vertebrae.

**Comment by Malaika68** [comment]
Okay Great..
